name: CI

# Controls when the action will run.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build_and_test:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v4

      # Sets up a specific version of Node.js.
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # Installs all dependencies from package-lock.json.
      - name: Install dependencies
        run: npm ci

      # Builds the TypeScript project to catch any compilation errors.
      - name: Build
        run: npm run build

      # Runs the tests to ensure all functionality is working as expected.
      - name: Run tests
        run: npm test